version: '3'

networks:
  default:
    driver: bridge

services:
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ${DATA_PATH_HOST}/app:/app